### ISSUE TITLE
Add host UUID as identifying feature [Feature Request]

### ISSUE THREAD

**Issue by benbasscom** [richiercyrus/Venator#11]
Could you add the host UUID as an additional field along with the hostname?  I have found hostnames can change more often then I would like, which can make correlating data across different runs over a longer period of time a bit complicated. 

Thank you!

**Comment by richiercyrus** [comment]
Sure thing. I'll dig into this by the end of the week. Thanks @benbasscom!

**Comment by 0xmachos** [comment]
@richiercyrus I've open PR #12 which adds this functionality.

**Comment by richiercyrus** [comment]
Added UUID as an additional field. Thanks again for the suggestion @benbasscom. Also thanks @0xmachos for the quick response!
