### ISSUE TITLE
Chrome extension collection NoneType

### ISSUE THREAD

**Issue by tommyskg** [richiercyrus/Venator#14]
Encountered this issue when running Venator on macOS 10.14.4 and current Chrome version (``74.0.3729.131``):

    [+] Gathering Chrome Extensions data.
    Traceback (most recent call last):
      File "Venator.py", line 728, in <module>
        getChromeExtensions(chromeEx,outfile)
      File "Venator.py", line 308, in getChromeExtensions
        extensions.update({"extension_update_url":manifest_json.get("update_url").strip('u\'')})
    AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by richiercyrus** [comment]
I'll take a look at this soon. Thanks for bringing this up.

**Comment by tommyskg** [comment]
Tested and verified that the fix above works. Thanks!
