### ISSUE TITLE
Adding requirements.txt

### ISSUE THREAD

**Issue by felixguerrero12** [richiercyrus/Venator#6]
Adding a requirements.txt file to have the ability to execute pip to install the required packages:

>  pip install -r requirements.txt

Most of the libraries are standard python libraries but others are not:
os
datetime
logging
math
sys
plistlib
string
struct
xml.parsers.expat
subprocess
json
socket
Foundation
Quartz
argparse
ctypes
ctypes.util
objc
platform
time
hashlib

This is also running on python2.

**Comment by felixguerrero12** [comment]
You can run something like this to show all the packages you have:
> for i in `cat libraries.txt`; do pip freeze | grep $i; done

**Comment by richiercyrus** [comment]
All of the libraries are native to macOS, and should run out of the box. /usr/bin/python may need to be specified.

**Comment by felixguerrero12** [comment]
I would recommend adding the interpreter to the top of the python script:
#!/usr/bin/python

If you run python it will automatically understand which one to use.
@richiercyrus

**Comment by richiercyrus** [comment]
That’s for the feedback, I’ll add that in!
