### ISSUE TITLE
UnboundLocalError: local variable 'progExecutable'

### ISSUE THREAD

**Issue by dlaynes** [richiercyrus/Venator#7]
Hi, I'm getting this error when running the script on MacOS Mojave. Thanks for your help

`[+] Gathering users on the system.

[+] Gathering System Intergrity Protection status.

[+] Getting system information.

[+] Gathering Install History data.

[+] Gathering Gatekeeper status.

[+] Gathering current network connections.

[+] Gathering Environment Variables.

[+] Gathering Periodic Scripts.

[+] Gathering current cron jobs.

[+] Gathering Emond Rules.

[+] Gathering Launch Agent data.

[+] Gathering Launch Daemon data.

[+] Gathering Kernel Extensions data.

[+] Gathering Applications for each user.

[+] Gathering installed Event Taps.

[+] Gathering Bash History data.

[+] Gathering Launch Agent data.

[+] Gathering Chrome Extensions data.

[+] Gathering Firefox Extensions data.

[+] Gathering Safari Extensions data.

[+] Gathering Login Items for each user.

[+] Gathering Applications for each user.

[+] Gathering Launch Agent data.

[+] Gathering Chrome Extensions data.

[+] Gathering Firefox Extensions data.

[+] Gathering Applications for each user.

[!!!!!] System Integrity Protection is disabled. Gathering additional data launch agent/daemon data.

[+] Gathering Launch Agent data.

[+] Gathering Launch Daemon data.

Traceback (most recent call last):

  File "./Venator.py", line 674, in <module>

    output_list.append(getLaunchDaemons('/System/Library/LaunchDaemons',outfile))

  File "./Venator.py", line 220, in getLaunchDaemons

    parsedDaemon = parseAgentsDaemons(daemon,path)

  File "./Venator.py", line 194, in parseAgentsDaemons

    parsedPlist.update({"signing_info":checkSignature(progExecutable)})

UnboundLocalError: local variable 'progExecutable' referenced before assignment`

**Comment by richiercyrus** [comment]
Thanks for this. I’ll check this out!

**Comment by richiercyrus** [comment]
I added some additional checking for this issue, let me know if you run into additional issues. Thanks again for flagging this.

**Comment by dlaynes** [comment]
With the new changes, somehow the variable becomes undefined in this step:

File "./Venator.py", line 194, in parseAgentsDaemons
    if os.path.exists(progExecutable):
  UnboundLocalError: local variable 'progExecutable' referenced before assignment

**Comment by richiercyrus** [comment]
Just pushed another fix. See if that will do the trick.

**Comment by dlaynes** [comment]
It generates the json file. Thanks
